### ISSUE TITLE
ip geographical location

### ISSUE THREAD

**Issue by physio** [404labfr/laravel-auth-checker#1]
good morning, sorry for my orrible english.
i have installed laravel-auth-checker and i think that this is a good solution for increase the security of a project. thanks @404labfr.

i can see that you register the ip of user login. with some packages (http://lyften.com/projects/laravel-geoip/ for ex.) we can locate approximately the position of the user. If i want to increase the security, for example if i sure that my users logons always from a single country (suppose for a crm for ex.), where i can edit your package for insert the control? i think the better solution is create a new middleware. right?

reguards

**Comment by MarceauKa** [comment]
Hi @physio, thank you for your issue!
Yep, we're thinking about this feature for the future.
If you want to implement it, look at built-in events.

**Comment by physio** [comment]
thank you so much.
