### ISSUE TITLE
Problem with migration.

### ISSUE THREAD

**Issue by w00p** [404labfr/laravel-auth-checker#3]
Hi, 

I had a problem migrating the 2 tables, i had to rename 2017_03_25_124200_create_logins_table.php to 2018_03_25_124200_create_logins_table.php

Devices table should migrate first because of the reference to to foreign in create login table.

**Comment by MarceauKa** [comment]
Hi! Thank you for your issue.
I'll check that :)

**Comment by MarceauKa** [comment]
The `users_table` migration is by default to "2014_..." so this package migrations are loaded after and don't cause any problem.

**Comment by MarceauKa** [comment]
Look at the new version [1.1.0](https://github.com/404labfr/laravel-auth-checker/releases/tag/1.1.0)

**Comment by SiebeVE** [comment]
The problem remains, because the logins table has a foreign key to the devices table while it hasn't been created yet.
