### ISSUE TITLE
How to use with API? 

### ISSUE THREAD

**Issue by devingray** [404labfr/laravel-auth-checker#4]
Would it be possible to use this package with an API, I.E a react native app, posting data to the api where we save logins and devices

**Comment by MarceauKa** [comment]
Hi, no plan for that but you can open a PR :)

**Comment by patrickwarner** [comment]
Would be great to see a PR for this added functionality. Looks like a promising package, however I won't be able to use it unless it supports Laravel Passport authentication.

This isn't a high priority for me right now, but if I ever have some free time and try to go this route with this package I'll submit a PR.
