### ISSUE TITLE
Laravel version requirement

### ISSUE THREAD

**Issue by acharkizakaria** [404labfr/laravel-auth-checker#7]
Hi guys, could you please tell me why we could use the plugin just with the recent version 'laravel/framework 5.4.*' and not with the other 'old' releases '5.3', '5.2' ..

I think it will be better if we could adjust it :)

Thanks in advance.

**Comment by MarceauKa** [comment]
Hi, it's because the plugin is not compatible with Laravel under 5.4.
But you can send a PR :p

**Comment by denjaland** [comment]
Are there any compatibility issues with 5.5 that you are aware off?
I'll upgrade now and check - if it works, I'll send a PR?

**Comment by MarceauKa** [comment]
Yeay, please :)
